
version: "3.8"
 
services:
  
  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    restart: always
    command: mongod

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/log/:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672

  api:
    build: api
    container_name: api
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=local
    volumes:
      - "$PWD/config:/home/conf"
    ports: 
      - "8089:8080"
    depends_on:
      - db

  labeler:
    build: labeler
    container_name: labeler
    environment:
      - SPRING_PROFILES_ACTIVE=local
    restart: always
    volumes:
      - "$PWD/config:/home/conf"
    ports: 
      - "8084:8080"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./api/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000

      